controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

carList:
    path: /nos_voitures
    controller: App\Controller\CarController::car_list
    methods: [POST]